version: '3'

services:
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: server
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: baby-tracker
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: server
      ME_CONFIG_MONGODB_ADMINPASSWORD: test

  client:
    build: client
    command: yarn start
    environment:
      REACT_APP_SERVER: http://0.0.0.0:8084
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 1
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app

  server:
    build: server
    command: yarn dev
    environment:
      NODE_ENV: development
      DATABASE_URL: mongodb://server:test@mongo:27017/baby-tracker
    ports:
      - 8084:8084
    volumes:
      - ./server:/usr/src/app
